xut: minor fixes and clean-up.

diff --git a/xut b/xut
--- a/xut
+++ b/xut
@@ -35,7 +35,7 @@ msg() {
 	elif [ "${1}" = "warn" ]; then printf "%s\n" "${yellow}(~~) Warning: ${2} ${reset_colour}"
 	elif [ "${1}" = "info" ]; then printf "%s\n" "${green}(~>) Info:  ${2} ${reset_colour}"
 	else printf "%s\n" "${red}(!!) Error: ${1} is not recognised for msg() ${reset_colour}" && exit 1 
-	 fi
+	fi
 }
 
 usage() {
@@ -102,17 +102,20 @@ integrate_xtra_templates() {
 }
 
 xbps_src_command() {
-	cd "$conf_workdir"/"$default_repo_dir" || msg error "Cannot change directory into $default_repo_dir"
-	./xbps-src clean || msg error "Cannot execute <xbps-src clean>."
-	./xbps-src "$op_xbps_src" || msg error "Cannot execute <xbps-src $op_xbps_src>"
+	if [ -n "$op_xbps_src" ]; then
+		cd "$conf_workdir"/"$default_repo_dir" || msg error "Cannot change directory into $default_repo_dir"
+		./xbps-src clean || msg error "Cannot execute <xbps-src clean>."
+		./xbps-src "$op_xbps_src" || msg error "Cannot execute <xbps-src $op_xbps_src>"; fi
 }
 
 install_packages() {
+	[ -z "$packages" ] && msg warn "No packages for installation..." && exit 0
 	package_list="$(echo "$packages" | tr ',' ' ')"
 	export package_list="$package_list"
-	[ -z "$package_list" ] && msg error "Nothing to do..."
 	for package in $package_list; do 
 		cd "$conf_workdir"/"$default_repo_dir" -  && ./xbps-src pkg "$package"
+		cmd_status=$?
+		[ "$cmd_status" != 0 ] && msg error "$package build failed, see above!"
 	done
 	# shellcheck disable=SC2086
 	xi $package_list
@@ -135,12 +138,11 @@ else msg info "Using the default configuration."
 fi
 # Check for needed dirs.
 [ ! -e "$conf_workdir/logs" ] && mkdir -pv "$conf_workdir/logs" 
-# clean or zap repos before other ops
-[ -n "$op_xbps_src" ] && xbps_src_command
-# Clone repos if needed 
+xbps_src_command
 include_additional_repos
+# Clone repos if needed
 retrieve_repos
-[ "$op_sync" = 1 ] && sync_repos
+sync_repos
 #Enable building restricted packages
 if grep -q "XBPS_ALLOW_RESTRICTED=yes" "$conf_workdir"/"$default_repo_dir"/etc/conf ; then
 	msg info "Building restricted packages is enabled!"
@@ -152,7 +154,7 @@ if [ ! -e "$conf_workdir"/"$default_repo_dir"/masterdir-"$(xbps-uhelper arch)"/u
 then  op_xbps_src="binary-bootstrap" && xbps_src_command; fi
 #all template dirs are copied 
 integrate_xtra_templates
-[ -n "$packages" ] && install_packages
+install_packages
 }
 
 #Keep only 5 log files, including the current one.
